name: CI

on:
  push:
    branches:
      - main
      - feat/registration-day1
  pull_request: {}

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write          # для ghcr
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache Poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        run: pip install poetry==1.8.2

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Ruff (lint)
        run: poetry run ruff check consultplace_bot tests

      - name: Mypy (type-check)
        run: poetry run mypy consultplace_bot --pretty

      - name: Pytest
        run: poetry run pytest -q --cov=consultplace_bot

########################################
# Docker image (только для main)
########################################
      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max